DROP TABLE IF EXISTS events;
CREATE TABLE events (
    eventID INTEGER PRIMARY KEY AUTOINCREMENT,
    eventName TEXT NOT NULL,
    dateEvent DATETIME,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    eventDescription TEXT NOT NULL
);
